package com.ejercicios.ejercicio62.datos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Frecuencia implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Frecuencia cardiaca")
	private java.lang.Integer frecuencia;

	public Frecuencia() {
	}

	public java.lang.Integer getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(java.lang.Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Frecuencia(java.lang.Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

}