package com.ejercicios.ejercicio64.datos;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Paciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Identificador del paciente")
	private java.lang.String identificador;
	@org.kie.api.definition.type.Label("Nombre del paciente")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("Apellidos del paciente")
	private java.lang.String apellidos;
	@org.kie.api.definition.type.Label("Fecha de nacimento")
	private String fecha;
	@org.kie.api.definition.type.Label("Enfermedad del paciente")
	private java.lang.Boolean enfermo;

	@org.kie.api.definition.type.Label("Frecuencia cardiaca mínima")
	private java.lang.Integer fminima;

	@org.kie.api.definition.type.Label("Frecuencia cardiaca máxima")
	private java.lang.Integer fmaxima;

	public Paciente() {
	}

	public java.lang.String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(java.lang.String identificador) {
		this.identificador = identificador;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(java.lang.String apellidos) {
		this.apellidos = apellidos;
	}

	public java.lang.Boolean getEnfermo() {
		return this.enfermo;
	}

	public void setEnfermo(java.lang.Boolean enfermo) {
		this.enfermo = enfermo;
	}

	public java.lang.Integer getFminima() {
		return this.fminima;
	}

	public void setFminima(java.lang.Integer fminima) {
		this.fminima = fminima;
	}

	public java.lang.Integer getFmaxima() {
		return this.fmaxima;
	}

	public void setFmaxima(java.lang.Integer fmaxima) {
		this.fmaxima = fmaxima;
	}

	public java.lang.String getFecha() {
		return this.fecha;
	}

	public void setFecha(java.lang.String fecha) {
		this.fecha = fecha;
	}

	public Paciente(java.lang.String identificador, java.lang.String nombre,
			java.lang.String apellidos, java.lang.String fecha,
			java.lang.Boolean enfermo, java.lang.Integer fminima,
			java.lang.Integer fmaxima) {
		this.identificador = identificador;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fecha = fecha;
		this.enfermo = enfermo;
		this.fminima = fminima;
		this.fmaxima = fmaxima;
	}

}