package com.ejerciciosjbpm.ejercicio61.datos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Paciente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Identificador del paciente")
	private java.lang.String identificador;
	@org.kie.api.definition.type.Label(value = "Nombre del paciente")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label(value = "Apellidos del paciente")
	private java.lang.String apellidos;
	@org.kie.api.definition.type.Label(value = "Fecha de nacimiento del paciente")
	private java.lang.String fecha;
	@org.kie.api.definition.type.Label(value = "Enfermedad del paciente")
	private java.lang.Boolean enfermo;

	public Paciente() {
	}

	public java.lang.String getIdentificador() {
		return this.identificador;
	}

	public void setIdentificador(java.lang.String identificador) {
		this.identificador = identificador;
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(java.lang.String apellidos) {
		this.apellidos = apellidos;
	}

	public java.lang.String getFecha() {
		return this.fecha;
	}

	public void setFecha(java.lang.String fecha) {
		this.fecha = fecha;
	}

	public java.lang.Boolean getEnfermo() {
		return this.enfermo;
	}

	public void setEnfermo(java.lang.Boolean enfermo) {
		this.enfermo = enfermo;
	}

	public Paciente(java.lang.String identificador, java.lang.String nombre,
			java.lang.String apellidos, java.lang.String fecha,
			java.lang.Boolean enfermo) {
		this.identificador = identificador;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fecha = fecha;
		this.enfermo = enfermo;
	}

}